# Generated by Django 3.2.9 on 2021-11-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='on_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='on_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
